// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

export type AllDocumentTypes = ArticleDocument;

/**
 * Item in *Stories → Default → Primary → Articles*
 */
export interface StoriesSliceDefaultPrimaryArticlesItem {
  /**
   * story image field in *Stories → Default → Primary → Articles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.default.primary.articles[].story_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  story_image: prismic.ImageField<never>;

  /**
   * Title field in *Stories → Default → Primary → Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.default.primary.articles[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Stories → Default → Primary*
 */
export interface StoriesSliceDefaultPrimary {
  /**
   * Articles field in *Stories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.default.primary.articles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<StoriesSliceDefaultPrimaryArticlesItem>
  >;
}

/**
 * Default variation for Stories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Stories*
 */
type StoriesSliceVariation = StoriesSliceDefault;

/**
 * Stories Shared Slice
 *
 * - **API ID**: `stories`
 * - **Description**: Stories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoriesSlice = prismic.SharedSlice<
  "stories",
  StoriesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      AllDocumentTypes,
      StoriesSlice,
      StoriesSliceDefaultPrimaryArticlesItem,
      StoriesSliceDefaultPrimary,
      StoriesSliceVariation,
      StoriesSliceDefault,
    };
  }
}
